[package]
name = "nevy_quic"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
log.workspace = true
nevy = { path = "../.." }
quinn-proto = { version = "0.11", features = ["rustls"] }
quinn-udp = "0.5"
bytes = "1.6.0"
